name: Flutter CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Flutter setup
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.x'
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Format code
        run: flutter format --set-exit-if-changed .
      - name: Static analysis
        run: flutter analyze
      - name: Flutter tests
        run: flutter test
