name: Flutter CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Install dependencies
        working-directory: ./app/healthtracker
        run: flutter pub get
      - name: Clean cache
        working-directory: ./app/healthtracker
        run: flutter pub cache repair
      - name: Flutter tests
        working-directory: ./app/healthtracker
        run: flutter test
